### PR TITLE
feat: rename vertical to radio prop

### PR DESCRIPTION
**Pull request by v8tenko**

### CODE REVIEW

**Review by vsesh — APPROVED** [review]
I think it's the major change

**Comment by v8tenko** [comment]
> I think it's the major change

why is it? users just want to use with prop "radio"

**Comment by vsesh** [comment]
>> why is it? users just want to use with prop "radio"

Somebody could have started using the `vertical` option. After the minor release, their business logic will be broken.

**Comment by v8tenko** [comment]
> > > why is it? users just want to use with prop "radio"
> 
> Somebody could have started using the `vertical` option. After the minor release, their business logic will be broken.

yes, it is. I didn't understand right. vertical mode are in test right now, so it is ok

**Pull request merged**
